### PR TITLE
[WIP] Add HPL

### PR DESCRIPTION
**Pull request by Ezibenroc**
I think it would be nice to test HPL in the Jenkins build. This is a tentative, the script from the org file seems to work properly on a fresh G5K install, but maybe I missed something.

Roadmap:
- [ ] Successful run on Jenkins
- [x] Test for vanilla HPL
- [ ] Test for optimized HPL
- [ ] Test for optimized HPL with huge pages?

Also, I don't know if I should try to minimize the patch, e.g. by removing the useless comments and options in the Makefile, or if I should keep it as close to the original Makefile model.

### CODE REVIEW

**Comment by adegomme** [comment]
Hi, 
the verbosity is not an issue I think (and then you have to keep to copyright anyway). 
But I don't like the patch format in this case, as you are just creating two files in the end. You can just add them to the git, and use cp in the test instead of patch, it would make things more readable (or do a real diff between a provided makefile and yours, to have a readable patch).

Can you change your PR in this regard ?
Thanks

**Comment by mquinson** [comment]
That's a damn good idea, thanks! I hope to see the other tests anytime soon. That'd be a great way to address https://github.com/simgrid/simgrid/issues/205 , amongst others.

**Comment by Ezibenroc** [comment]
I have just noticed the [`jenkins.sh`](https://github.com/simgrid/SMPI-proxy-apps/blob/master/jenkins.sh#L13) file, I forgot to add `HPL.org` here, so the new test will probably not be executed.

Maybe we could replace the for loop by a `for org in *.org` ?

> That's a damn good idea, thanks! I hope to see the other tests anytime soon. That'd be a great way to address simgrid/simgrid#205 , amongst others.

Sure, I will work on this!

**Comment by adegomme** [comment]
Indeed, I didn't notice that oddity yet

**Comment by adegomme** [comment]
15:13:02 51/51 Test #51: HPL_vanilla ......................   Passed   53.44 sec

(I installed atlas anyway)

**Pull request merged**
